/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 blaszak.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Blaszak(props) {
  const { nodes, materials } = useGLTF('/blaszak.glb')
  const {width,height,depth}=props.box
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.calosc.geometry} material={materials.drzwi} position={[0, 1.25, 0]} scale={[depth/2.5,1,width/2.5]} />
      <mesh geometry={nodes.dach.geometry} material={materials.drzwi} position={[0, 2.38, 0]} rotation={[0, 0, 0.07]} scale={[depth/2.5,1,width/2.5]} />
      <mesh geometry={nodes.ramka.geometry} material={materials.czarny} position={[1.26*depth/2.5, 1.16, 0]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes['drzwi-cale'].geometry} material={materials.drzwi} position={[1.27*depth/2.5, 1.16, 0]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.klamka.geometry} material={materials.klamki} position={[1.28*depth/2.5, 1.18, 0]} />
    </group>
  )
}

useGLTF.preload('/blaszak.glb')
