/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 textura.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/textura.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bryla.geometry} material={materials.drzwi} position={[0, 1.25, 0]} />
      <mesh geometry={nodes.dach.geometry} material={materials.drzwi} position={[0, 2.37, 0]} rotation={[0, 0, 0.11]} />
      <mesh geometry={nodes.spust.geometry} material={materials['Rynny.002']} position={[-1.31, 1.19, -1.28]} rotation={[Math.PI, -1.3, Math.PI]} />
      <mesh geometry={nodes.rynna.geometry} material={materials['Rynny.002']} position={[-1.32, 2.21, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
      <mesh geometry={nodes.bryla1.geometry} material={materials.drzwi} position={[0, 1.25, 0]} />
      <mesh geometry={nodes.dach1.geometry} material={materials.drzwi} position={[0, 2.55, 0]} rotation={[0, 0, -0.08]} />
      <mesh geometry={nodes.spust1.geometry} material={materials['Rynny.001']} position={[1.28, 1.29, -1.25]} rotation={[Math.PI, -1.3, Math.PI]} />
      <mesh geometry={nodes.rynna1.geometry} material={materials['Rynny.001']} position={[1.3, 2.43, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
      <mesh geometry={nodes.dach2.geometry} material={materials.drzwi} position={[0, 2.57, -0.01]} rotation={[0.08, -1.57, 0]} />
      <mesh geometry={nodes.bryla2.geometry} material={materials['drzwi.007']} position={[0, 1.25, 0]} />
      <mesh geometry={nodes.spust2.geometry} material={materials['Rynny.003']} position={[-1.22, 1.3, 1.3]} />
      <mesh geometry={nodes.rynna2.geometry} material={materials['Rynny.003']} position={[0.03, 2.45, 1.3]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dach3.geometry} material={materials.drzwi} position={[0, 2.58, 0.04]} rotation={[-0.08, 1.57, 0]} />
      <mesh geometry={nodes.rynna3.geometry} material={materials.Rynny} position={[-0.04, 2.45, -1.3]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.spust3.geometry} material={materials.Rynny} position={[-1.22, 1.29, -1.29]} />
      <mesh geometry={nodes.bryla3.geometry} material={materials['drzwi.008']} position={[0, 1.25, 0]} />
      <mesh geometry={nodes.dach4.geometry} material={materials.drzwi} position={[0, 2.64, 0.65]} rotation={[0.26, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.rynna4.geometry} material={materials.Rynny} position={[-0.04, 2.45, -1.3]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.spust4.geometry} material={materials.Rynny} position={[-1.22, 1.29, -1.29]} />
      <mesh geometry={nodes.bryla4.geometry} material={materials['drzwi.008']} position={[0, 1.25, 0]} />
      <mesh geometry={nodes.dach4v2.geometry} material={materials['drzwi.009']} position={[0, 2.65, -0.63]} rotation={[-0.26, Math.PI / 2, 0]} />
      <mesh geometry={nodes.spust4v2.geometry} material={materials['Rynny.004']} position={[-1.27, 1.3, 1.3]} />
      <mesh geometry={nodes.rynna4v2.geometry} material={materials['Rynny.004']} position={[-0.02, 2.45, 1.3]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes['drzwi-male-bok'].geometry} material={materials.drzwi} position={[0.35, 0.99, 1.26]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['dzwi-male-obramowka'].geometry} material={materials.czarny} position={[0.35, 1.01, 1.25]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Klamka.geometry} material={materials.klamki} position={[0.01, 1.04, 1.26]} />
      <mesh geometry={nodes['dzwi-calosc'].geometry} material={materials['drzwi.001']} position={[1.27, 1.16, 0]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes['podwojnedzwi-front001'].geometry} material={materials['drzwi.003']} position={[1.27, 1.16, 0.57]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes['podwojnedzwi-front002'].geometry} material={materials['drzwi.006']} position={[1.27, 1.16, 0.57]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.pokretlo.geometry} material={materials.klamki} position={[1.28, 1.18, 0]} />
      <mesh geometry={nodes.ramka003.geometry} material={materials.czarny} position={[1.25, 1.16, 0]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.klamkafront.geometry} material={materials['klamki.001']} position={[1.27, 1.18, -0.07]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.swietlik.geometry} material={materials['Material.001']} position={[0.8, 2.33, 1.26]} rotation={[Math.PI / 2, 0, 0]} />
      <group position={[0.89, 1.96, -1.26]}>
        <mesh geometry={nodes.Cube002.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube002_1.geometry} material={materials.okno} />
      </group>
    </group>
  )
}

useGLTF.preload('/textura.glb')
